/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as CircuitsIndexRouteImport } from './routes/circuits/index'
import { Route as CircuitsCircuitIdRouteImport } from './routes/circuits/$circuitId'
import { Route as SeasonsIndexRouteImport } from './routes/seasons/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsIndexRoute = CircuitsIndexRouteImport.update({
  id: '/circuits/',
  path: '/circuits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsCircuitIdRoute = CircuitsCircuitIdRouteImport.update({
  id: '/circuits/$circuitId',
  path: '/circuits/$circuitId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIndexRoute = SeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/circuits/$circuitId': typeof CircuitsCircuitIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/circuits/$circuitId': typeof CircuitsCircuitIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/circuits': typeof CircuitsIndexRoute
  '/seasons': typeof SeasonsIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/circuits/$circuitId': typeof CircuitsCircuitIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/circuits/$circuitId'
    | '/teams/$teamId'
    | '/circuits/'
    | '/seasons/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/circuits/$circuitId'
    | '/teams/$teamId'
    | '/circuits'
    | '/seasons'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/circuits/$circuitId'
    | '/teams/$teamId'
    | '/circuits/'
    | '/seasons/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  CircuitsCircuitIdRoute: typeof CircuitsCircuitIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  CircuitsIndexRoute: typeof CircuitsIndexRoute
  SeasonsIndexRoute: typeof SeasonsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/': {
      id: '/circuits/'
      path: '/circuits'
      fullPath: '/circuits/'
      preLoaderRoute: typeof CircuitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/$circuitId': {
      id: '/circuits/$circuitId'
      path: '/circuits/$circuitId'
      fullPath: '/circuits/$circuitId'
      preLoaderRoute: typeof CircuitsCircuitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/': {
      id: '/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof SeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  CircuitsCircuitIdRoute: CircuitsCircuitIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  CircuitsIndexRoute: CircuitsIndexRoute,
  SeasonsIndexRoute: SeasonsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
